---
- name: Install Wazuh Manager and Agent
  hosts: all
  become: yes
  tasks:
    - name: Add Wazuh repository key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: deb https://packages.wazuh.com/4.x/apt/ stable main
        state: present

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Wazuh manager
      apt:
        name: wazuh-manager
        state: present

    - name: Install Wazuh agent
      apt:
        name: wazuh-agent
        state: present
